'use client'
import {ChangeEvent,useEffect,useMemo,useState} from 'react'
import {Download,HardDrive,Paperclip,RefreshCcw,RotateCcw,Search,Trash2} from 'lucide-react'
import {supabase} from '@/lib/supabase'
import {useAuth} from '@/app/components/AuthProvider'
import type {Project,ProjectFile,Task} from '@/lib/types'

const MAX=50*1024*1024
function fmt(n:number){if(n>=1024**3)return `${(n/1024**3).toFixed(2)} GB`;if(n>=1024**2)return `${(n/1024**2).toFixed(1)} MB`;if(n>=1024)return `${Math.ceil(n/1024)} KB`;return `${n} B`}
function safeName(name:string){return name.replace(/[^a-zA-Z0-9._가-힣-]/g,'_')}

export default function FilesPage(){
 const {staff}=useAuth();const manager=staff?.role==='ADMIN'||staff?.role==='MANAGER';const admin=staff?.role==='ADMIN'
 const [files,setFiles]=useState<ProjectFile[]>([]),[projects,setProjects]=useState<Project[]>([]),[tasks,setTasks]=useState<Task[]>([])
 const [tab,setTab]=useState<'active'|'trash'>('active'),[q,setQ]=useState(''),[usage,setUsage]=useState({bytes:0,count:0,quota_bytes:1073741824})
 const [quotaGb,setQuotaGb]=useState('1'),[scope,setScope]=useState<'project'|'task'>('project'),[scopeId,setScopeId]=useState(''),[uploading,setUploading]=useState(false),[msg,setMsg]=useState('')
 async function load(){const [{data:f,error:fe},{data:p},{data:t},{data:u}]=await Promise.all([supabase.from('project_file').select('*,uploader:uploaded_by(name),deleter:deleted_by(name),project:project_id(project_name),task:task_id(title)').order('created_at',{ascending:false}),supabase.from('project').select('*,client:client_id(name)').is('deleted_at',null).order('created_at',{ascending:false}),supabase.from('task').select('*').is('deleted_at',null).order('created_at',{ascending:false}),supabase.rpc('app_project_files_storage_usage')]);if(fe)setMsg(fe.message);setFiles((f||[]) as ProjectFile[]);setProjects((p||[]) as Project[]);setTasks((t||[]) as Task[]);const x=(u||{}) as any;if(x&&typeof x==='object'){const v={bytes:Number(x.bytes||0),count:Number(x.count||0),quota_bytes:Number(x.quota_bytes||1073741824)};setUsage(v);setQuotaGb(String(Math.max(.1,Math.round(v.quota_bytes/1024**3*10)/10)))}}
 useEffect(()=>{if(staff)void (async()=>{await purgeExpired();await load()})()},[staff?.id])
 async function purgeExpired(){if(!manager)return;const {data}=await supabase.from('project_file').select('id,storage_path').not('deleted_at','is',null).lte('purge_after',new Date().toISOString());for(const x of data||[]){const rm=await supabase.storage.from('project-files').remove([x.storage_path]);if(!rm.error)await supabase.from('project_file').delete().eq('id',x.id)}}
 const percent=usage.quota_bytes?Math.round(usage.bytes/usage.quota_bytes*100):0
 const trashBytes=files.filter(x=>x.deleted_at).reduce((a,x)=>a+Number(x.size_bytes||0),0)
 const view=useMemo(()=>files.filter(x=>(tab==='trash'?!!x.deleted_at:!x.deleted_at)&&(!q.trim()||[x.file_name,x.project?.project_name,x.task?.title,x.uploader?.name].some(v=>String(v||'').toLowerCase().includes(q.trim().toLowerCase())))),[files,tab,q])
 async function upload(e:ChangeEvent<HTMLInputElement>){const selected=[...(e.target.files||[])];e.target.value='';if(!selected.length||!staff||!scopeId)return;const tooBig=selected.find(f=>f.size>MAX);if(tooBig){alert(`${tooBig.name} 파일이 50MB를 초과합니다.`);return}setUploading(true);setMsg('');const linkedTask=scope==='task'?tasks.find(t=>t.id===scopeId):null;for(let i=0;i<selected.length;i++){const file=selected[i];const base=scope==='task'?`tasks/${scopeId}`:`projects/${scopeId}`;const path=`${base}/${Date.now()}-${i}-${safeName(file.name)}`;const up=await supabase.storage.from('project-files').upload(path,file,{contentType:file.type||undefined,upsert:false});if(up.error){setMsg(`${file.name}: ${up.error.message}`);continue}const ins=await supabase.from('project_file').insert({project_id:scope==='project'?scopeId:(linkedTask?.project_id||null),task_id:scope==='task'?scopeId:null,file_name:file.name,logical_name:file.name,storage_path:path,content_type:file.type||null,size_bytes:file.size,uploaded_by:staff.id});if(ins.error){await supabase.storage.from('project-files').remove([path]);setMsg(`${file.name}: ${ins.error.message}`)}}setUploading(false);await load()}
 async function download(x:ProjectFile){const {data,error}=await supabase.storage.from('project-files').createSignedUrl(x.storage_path,120);if(error)alert(error.message);else window.open(data.signedUrl,'_blank')}
 async function trash(x:ProjectFile){if(!manager||!staff)return;if(!confirm(`${x.file_name}을 휴지통으로 이동할까요?`))return;const now=new Date(),purge=new Date(now.getTime()+30*86400000);const {error}=await supabase.from('project_file').update({deleted_at:now.toISOString(),deleted_by:staff.id,purge_after:purge.toISOString()}).eq('id',x.id);if(error)alert(error.message);else load()}
 async function restore(x:ProjectFile){if(!manager)return;const {error}=await supabase.from('project_file').update({deleted_at:null,deleted_by:null,purge_after:null}).eq('id',x.id);if(error)alert(error.message);else load()}
 async function permanent(x:ProjectFile){if(!manager)return;if(!confirm(`${x.file_name}을 완전히 삭제할까요?\n복구할 수 없습니다.`))return;const rm=await supabase.storage.from('project-files').remove([x.storage_path]);if(rm.error){alert(rm.error.message);return}const db=await supabase.from('project_file').delete().eq('id',x.id);if(db.error){alert(db.error.message);return}load()}
 async function emptyTrash(){if(!manager)return;const trash=files.filter(x=>x.deleted_at);if(!trash.length)return;if(!confirm(`휴지통 ${trash.length}개 파일을 모두 완전히 삭제할까요?`))return;const paths=trash.map(x=>x.storage_path);for(let i=0;i<paths.length;i+=100){const rm=await supabase.storage.from('project-files').remove(paths.slice(i,i+100));if(rm.error){alert(rm.error.message);return}}const db=await supabase.from('project_file').delete().in('id',trash.map(x=>x.id));if(db.error){alert(db.error.message);return}load()}
 async function saveQuota(){if(!admin)return;const gb=Number(quotaGb);if(!Number.isFinite(gb)||gb<=0){alert('용량을 올바르게 입력해 주세요.');return}const {error}=await supabase.from('file_storage_setting').update({quota_bytes:Math.round(gb*1024**3),updated_at:new Date().toISOString(),updated_by:staff?.id||null}).eq('singleton',true);if(error)alert(error.message);else load()}
 return <>
  <div className="pageHead"><div><h1>자료실</h1><p>프로젝트·업무 파일을 한곳에서 보관하고 휴지통과 저장공간을 관리합니다.</p></div><button className="secondary" onClick={()=>load()}><RefreshCcw size={14}/> 새로고침</button></div>
  <div className={`storageCard card ${percent>=90?'storageDanger':percent>=80?'storageWarn':''}`}><div className="storageTop"><div><HardDrive size={20}/><div><b>{fmt(usage.bytes)} 사용</b><small>관리 기준 {fmt(usage.quota_bytes)} · 파일 {usage.count}개</small></div></div><strong>{percent}%</strong></div><div className="storageBar"><span style={{width:`${Math.min(100,percent)}%`}}/></div>{percent>=90?<div className="storageAlert">저장공간 90% 이상입니다. 휴지통 영구삭제 또는 오래된 파일 정리를 권장합니다.</div>:percent>=80?<div className="storageAlert">저장공간 80% 이상입니다. 남은 용량을 확인해 주세요.</div>:null}<div className="storageMeta">휴지통 파일도 영구삭제 전까지 저장공간을 사용합니다. 현재 휴지통 약 {fmt(trashBytes)}.</div>{admin&&<div className="quotaEdit"><label>관리 기준 용량(GB)<input type="number" min="0.1" step="0.1" value={quotaGb} onChange={e=>setQuotaGb(e.target.value)}/></label><button className="secondary" onClick={saveQuota}>기준 저장</button></div>}</div>
  <div className="card fileUploadCenter"><div className="fileScope"><select value={scope} onChange={e=>{setScope(e.target.value as any);setScopeId('')}}><option value="project">프로젝트에 첨부</option><option value="task">업무에 첨부</option></select><select value={scopeId} onChange={e=>setScopeId(e.target.value)}><option value="">대상 선택</option>{(scope==='project'?projects:tasks).map((x:any)=><option key={x.id} value={x.id}>{scope==='project'?`${x.client?.name?x.client.name+' · ':''}${x.project_name}`:x.title}</option>)}</select></div><label className={'primary uploadBtn '+(!scopeId?'disabledUpload':'')}><Paperclip size={14}/>{uploading?'업로드 중...':'여러 파일 첨부'}<input type="file" multiple hidden disabled={!scopeId||uploading} onChange={upload}/></label><small>HWP/HWPX/PDF/엑셀/워드/사진/ZIP 등 · 파일당 최대 50MB</small></div>
  {msg&&<div className="error">{msg}</div>}
  <div className="fileToolbar"><div className="tabButtons"><button className={tab==='active'?'active':''} onClick={()=>setTab('active')}>보관 파일</button>{manager&&<button className={tab==='trash'?'active':''} onClick={()=>setTab('trash')}>휴지통 ({files.filter(x=>x.deleted_at).length})</button>}</div><div className="fileSearch"><Search size={15}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="파일명·프로젝트·업무 검색"/></div>{manager&&tab==='trash'&&<button className="dangerBtn" onClick={emptyTrash}><Trash2 size={14}/> 휴지통 비우기</button>}</div>
  <div className="tableWrap"><table className="filesTable"><thead><tr><th>파일명</th><th>연결</th><th>업로드</th><th>크기</th>{tab==='trash'&&<th>자동삭제</th>}<th>관리</th></tr></thead><tbody>{view.map(x=><tr key={x.id}><td><b>{x.file_name}</b>{x.version_no&&<small className="blockSmall">v{x.version_no}{x.is_latest?' · 최신':''}</small>}</td><td>{x.task?.title?<><span className="badge">업무</span> {x.task.title}</>:x.project?.project_name?<><span className="badge">프로젝트</span> {x.project.project_name}</>:'-'}</td><td>{x.uploader?.name||'-'}<small className="blockSmall">{new Date(x.created_at).toLocaleDateString('ko-KR')}</small></td><td>{fmt(Number(x.size_bytes||0))}</td>{tab==='trash'&&<td>{x.purge_after?new Date(x.purge_after).toLocaleDateString('ko-KR'):'-'}</td>}<td><div className="toolbar"><button className="secondary iconBtn" onClick={()=>download(x)}><Download size={14}/></button>{tab==='active'&&manager&&<button className="dangerBtn iconBtn" onClick={()=>trash(x)}><Trash2 size={14}/></button>}{tab==='trash'&&manager&&<><button className="secondary iconBtn" onClick={()=>restore(x)} title="복구"><RotateCcw size={14}/></button><button className="dangerBtn" onClick={()=>permanent(x)}>영구삭제</button></>}</div></td></tr>)}{!view.length&&<tr><td colSpan={tab==='trash'?6:5} className="empty">파일이 없습니다.</td></tr>}</tbody></table></div>
 </>
}
