'use client'
import { FormEvent,useEffect,useState } from 'react'
import { Sparkles } from 'lucide-react'
import { supabase } from '@/lib/supabase'

type Msg={role:'user'|'assistant';text:string;ai?:boolean}
export default function Assistant(){
 const [msg,setMsg]=useState('');const [busy,setBusy]=useState(false);const [messages,setMessages]=useState<Msg[]>([{role:'assistant',text:'업무비서입니다. “오늘 할 일”, “미수금”, “보완 프로젝트”, “이번 주 마감” 또는 거래처명을 물어보세요. 일반적인 업무 질문은 Claude AI로 답변합니다.'}]);const [snapshot,setSnapshot]=useState<any>({})
 async function load(){const [{data:t},{data:p},{data:r},{data:c}]=await Promise.all([supabase.from('task').select('title,status,due_date,priority,assignee:assignee_id(name),project:project_id(project_name)').is('deleted_at',null).neq('status','완료'),supabase.from('project').select('project_name,status,due_date,permit_type,contract_amount,client:client_id(name),manager:manager_id(name)').is('deleted_at',null).neq('status','취소'),supabase.from('v_receivables').select('*'),supabase.from('project_checklist').select('label,done,project:project_id(project_name)').eq('done',false)]);setSnapshot({tasks:t||[],projects:p||[],receivables:r||[],openChecklist:c||[]})}
 useEffect(()=>{load()},[])
 function localAnswer(q:string){const s=q.replace(/\s/g,'');const today=new Date();const week=new Date();week.setDate(today.getDate()+7);const td=today.toISOString().slice(0,10),wd=week.toISOString().slice(0,10);if(s.includes('미수')){const rows=(snapshot.receivables||[]).filter((x:any)=>Number(x.receivable)>0);return rows.length?`미수금 ${rows.length}건입니다.\n`+rows.map((x:any)=>`• ${x.client_name} / ${x.project_name}: ${Number(x.receivable).toLocaleString()}원`).join('\n'):'현재 미수금이 없습니다.'}if(s.includes('보완')){const rows=(snapshot.projects||[]).filter((x:any)=>x.status==='보완');return rows.length?`보완 프로젝트 ${rows.length}건입니다.\n`+rows.map((x:any)=>`• ${x.client?.name} / ${x.project_name} / 담당 ${x.manager?.name||'-'}`).join('\n'):'현재 보완 상태 프로젝트가 없습니다.'}if(s.includes('이번주')||s.includes('7일')||s.includes('마감')){const rows=(snapshot.tasks||[]).filter((x:any)=>x.due_date&&x.due_date<=wd&&x.due_date>=td);return rows.length?`7일 이내 마감 업무 ${rows.length}건입니다.\n`+rows.map((x:any)=>`• ${x.due_date} ${x.title} (${x.assignee?.name||'미지정'})`).join('\n'):'7일 이내 마감 업무가 없습니다.'}if(s.includes('오늘')||s.includes('할일')){const rows=(snapshot.tasks||[]).filter((x:any)=>x.due_date===td);return rows.length?`오늘 마감 업무 ${rows.length}건입니다.\n`+rows.map((x:any)=>`• ${x.title} / ${x.project?.project_name||'공통'} / ${x.assignee?.name||'미지정'}`).join('\n'):'오늘 마감 업무가 없습니다.'}const name=(snapshot.projects||[]).find((x:any)=>s.includes((x.client?.name||'').replace(/\s/g,''))||s.includes(x.project_name.replace(/\s/g,'')));if(name)return `${name.client?.name} / ${name.project_name}\n분야: ${name.permit_type}\n상태: ${name.status}\n담당: ${name.manager?.name||'미지정'}\n마감: ${name.due_date||'미정'}\n계약금액: ${Number(name.contract_amount||0).toLocaleString()}원`;return null}
 async function answer(q:string){const local=localAnswer(q);if(local)return {text:local,ai:false};const {data:{session}}=await supabase.auth.getSession();const r=await fetch('/api/ai',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session?.access_token||''}`},body:JSON.stringify({prompt:q,context:snapshot})});const d=await r.json();if(r.ok)return {text:d.text||'답변을 생성하지 못했습니다.',ai:true};return {text:`Claude AI 연결 전입니다. ${d.error||''}\n현재는 “오늘 할 일”, “이번 주 마감”, “보완”, “미수금”, 거래처명 조회를 사용할 수 있습니다.`,ai:false}}
 async function sendText(q:string){if(!q.trim()||busy)return;setMessages(m=>[...m,{role:'user',text:q}]);setMsg('');setBusy(true);const a=await answer(q);setMessages(m=>[...m,{role:'assistant',text:a.text,ai:a.ai}]);setBusy(false)}
 function submit(e:FormEvent){e.preventDefault();sendText(msg)}
 return <><div className="pageHead"><div><h1>AI 업무비서</h1><p>회사 DB를 즉시 조회하고, 필요하면 Claude API로 업무 질문을 처리합니다.</p></div></div><div className="assistantCard"><div className="chat">{messages.map((m,i)=><div key={i} className={`bubble ${m.role}`}>{m.ai&&<span className="aiTag"><Sparkles size={11}/> Claude</span>}{m.text.split('\n').map((v,j)=><span key={j}>{v}<br/></span>)}</div>)}{busy&&<div className="bubble assistant">답변 생성 중...</div>}</div><form className="chatInput" onSubmit={submit}><input value={msg} onChange={e=>setMsg(e.target.value)} placeholder="예: 코아텍 진행상황 / 미수금 / 이번 주 우선순위 정리해줘"/><button className="primary" disabled={busy}>질문</button></form><div className="chips">{['오늘 할 일','이번 주 마감','보완 프로젝트','미수금'].map(v=><button key={v} className="secondary" disabled={busy} onClick={()=>sendText(v)}>{v}</button>)}</div></div></>
}
