'use client'
import { ChangeEvent,useEffect,useState } from 'react'
import { useParams } from 'next/navigation'
import Link from 'next/link'
import { ArrowLeft,Download,Paperclip,Trash2,Link2 } from 'lucide-react'
import { supabase } from '@/lib/supabase'
import { useAuth } from '@/app/components/AuthProvider'
import type { Project,ChecklistItem,Task,ProjectFile } from '@/lib/types'

export default function ProjectDetail(){
 const {id}=useParams<{id:string}>(); const {staff}=useAuth(); const [project,setProject]=useState<Project|null>(null); const [check,setCheck]=useState<ChecklistItem[]>([]); const [tasks,setTasks]=useState<Task[]>([]); const [files,setFiles]=useState<ProjectFile[]>([]); const [uploading,setUploading]=useState(false)
 const can=staff?.role==='ADMIN'||staff?.role==='MANAGER'; const canUpload=staff?.role!=='VIEWER'; const [portalBusy,setPortalBusy]=useState(false)
 async function load(){const [{data:p},{data:c},{data:t},{data:f}]=await Promise.all([supabase.from('project').select('*,client:client_id(name,email,phone),manager:manager_id(name)').eq('id',id).single(),supabase.from('project_checklist').select('*').eq('project_id',id).order('sort_order'),supabase.from('task').select('*,assignee:assignee_id(name)').eq('project_id',id).is('deleted_at',null).order('due_date'),supabase.from('project_file').select('*,uploader:uploaded_by(name)').eq('project_id',id).order('created_at',{ascending:false})]);setProject(p as Project);setCheck((c||[]) as ChecklistItem[]);setTasks((t||[]) as Task[]);setFiles((f||[]) as ProjectFile[])}
 useEffect(()=>{load()},[id])
 async function toggle(x:ChecklistItem){await supabase.from('project_checklist').update({done:!x.done,done_at:!x.done?new Date().toISOString():null}).eq('id',x.id);load()}
 async function upload(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file||!staff)return;setUploading(true);const safe=file.name.replace(/[^a-zA-Z0-9._가-힣-]/g,'_');const path=`${id}/${Date.now()}-${safe}`;const {error}=await supabase.storage.from('project-files').upload(path,file,{contentType:file.type||undefined,upsert:false});if(error){alert(error.message);setUploading(false);return}const ins=await supabase.from('project_file').insert({project_id:id,file_name:file.name,storage_path:path,content_type:file.type||null,size_bytes:file.size,uploaded_by:staff.id});if(ins.error)alert(ins.error.message);setUploading(false);e.target.value='';load()}
 async function download(x:ProjectFile){const {data,error}=await supabase.storage.from('project-files').createSignedUrl(x.storage_path,60);if(error)alert(error.message);else window.open(data.signedUrl,'_blank')}
 async function remove(x:ProjectFile){if(!confirm(`${x.file_name} 파일을 삭제할까요?`))return;const {error}=await supabase.storage.from('project-files').remove([x.storage_path]);if(error){alert(error.message);return}await supabase.from('project_file').delete().eq('id',x.id);load()}
 async function createPortal(){setPortalBusy(true);const {data:{session}}=await supabase.auth.getSession();const r=await fetch('/api/portal/share',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session?.access_token||''}`},body:JSON.stringify({project_id:id,days:30})});const d=await r.json();setPortalBusy(false);if(!r.ok){alert(d.error||'포털 링크 생성 실패');return}const url=`${location.origin}/portal/${d.token}`;await navigator.clipboard.writeText(url);alert('고객 포털 링크를 복사했습니다. 30일간 유효합니다.')}
 if(!project)return <div className="centerInline">프로젝트 불러오는 중...</div>
 const done=check.filter(x=>x.done).length; const pct=check.length?Math.round(done/check.length*100):0
 return <><div className="pageHead"><div><Link href="/projects" className="backLink"><ArrowLeft size={15}/> 프로젝트 목록</Link><h1>{project.project_name}</h1><p>{project.client?.name} · {project.permit_type} · 담당 {project.manager?.name||'미지정'}</p></div><div className="toolbar">{can&&<button className="secondary" disabled={portalBusy} onClick={createPortal}><Link2 size={14}/> {portalBusy?'생성 중...':'고객 포털 링크'}</button>}<span className="badge">{project.status}</span></div></div>
 <div className="grid4"><div className="card metric"><span>마감일</span><strong className="smallMetric">{project.due_date||'미정'}</strong></div><div className="card metric"><span>계약금액</span><strong className="smallMetric">{Number(project.contract_amount).toLocaleString()}원</strong></div><div className="card metric"><span>체크리스트</span><strong>{done}/{check.length}</strong></div><div className="card metric"><span>진행률</span><strong>{pct}%</strong></div></div>
 <div className="twoCol section"><section><h2>인허가 체크리스트</h2><div className="card listCard"><div className="progress"><span style={{width:`${pct}%`}}/></div>{check.map(x=><label key={x.id} className="checkRow"><input type="checkbox" checked={x.done} onChange={()=>toggle(x)}/><span className={x.done?'doneText':''}>{x.label}</span>{x.is_required&&<small>필수</small>}</label>)}{!check.length&&<div className="empty">체크리스트가 없습니다.</div>}</div></section><section><div className="sectionTitle"><h2>첨부파일</h2>{canUpload&&<label className="secondary uploadBtn"><Paperclip size={14}/>{uploading?'업로드 중...':'파일 첨부'}<input type="file" hidden disabled={uploading} onChange={upload}/></label>}</div><div className="card listCard">{files.map(x=><div className="fileRow" key={x.id}><div><b>{x.file_name} {x.version_no&&<span className="badge">v{x.version_no}{x.is_latest?' · 최신':''}</span>}</b><small>{x.uploader?.name||'-'} · {x.size_bytes?`${Math.ceil(x.size_bytes/1024)} KB`:''}</small></div><div className="toolbar"><button className="secondary iconBtn" onClick={()=>download(x)} title="다운로드"><Download size={14}/></button>{can&&<button className="dangerBtn iconBtn" onClick={()=>remove(x)} title="삭제"><Trash2 size={14}/></button>}</div></div>)}{!files.length&&<div className="empty">첨부파일이 없습니다.</div>}</div></section></div>
 <section className="section"><h2>연결 업무</h2><div className="tableWrap"><table><thead><tr><th>업무</th><th>담당</th><th>우선순위</th><th>마감</th><th>상태</th></tr></thead><tbody>{tasks.map(x=><tr key={x.id}><td>{x.title}</td><td>{x.assignee?.name||'-'}</td><td>{x.priority}</td><td>{x.due_date||'-'}</td><td><span className="badge">{x.status}</span></td></tr>)}{!tasks.length&&<tr><td colSpan={5} className="empty">연결된 업무가 없습니다.</td></tr>}</tbody></table></div></section></>
}
