'use client'
import { useEffect,useState } from 'react'
import { supabase } from '@/lib/supabase'
import { useAuth } from '../components/AuthProvider'
import { hasPermission } from '@/lib/types'
import type { Task } from '@/lib/types'
export default function Dashboard(){
 const {staff}=useAuth();const [tasks,setTasks]=useState<Task[]>([]);const [projectCount,setProjectCount]=useState(0);const [correction,setCorrection]=useState(0);const [receivable,setReceivable]=useState(0);const [quoteAmount,setQuoteAmount]=useState(0);const [accepted,setAccepted]=useState(0);const [pendingApproval,setPendingApproval]=useState(0);const [taxMissing,setTaxMissing]=useState(0)
 useEffect(()=>{if(!staff)return;(async()=>{const now=new Date(),first=new Date(now.getFullYear(),now.getMonth(),1).toISOString();const own=staff.role==='STAFF'&&!staff.permissions?.all_projects;let tq=supabase.from('task').select('*,project:project_id(project_name),assignee:assignee_id(name)').is('deleted_at',null).neq('status','완료').order('due_date',{ascending:true,nullsFirst:false}).limit(12);let pq=supabase.from('project').select('*',{count:'exact',head:true}).is('deleted_at',null).in('status',['계약','진행중','보완']);let cq=supabase.from('project').select('*',{count:'exact',head:true}).is('deleted_at',null).eq('status','보완');if(own){tq=tq.eq('assignee_id',staff.id);pq=pq.eq('manager_id',staff.id);cq=cq.eq('manager_id',staff.id)}const canFinance=hasPermission(staff,'finance');const [{data:t},{count:p},{count:c},{data:r},{data:q},{count:a},{count:tx}]=await Promise.all([tq,pq,cq,canFinance?supabase.from('v_receivables').select('receivable'):Promise.resolve({data:[]}),supabase.from('quote').select('total_amount,status').is('deleted_at',null).gte('created_at',first),supabase.from('approval_request').select('id',{count:'exact',head:true}).eq('status','대기'),canFinance?supabase.from('billing').select('id',{count:'exact',head:true}).is('deleted_at',null).eq('tax_invoice_status','미발행'):Promise.resolve({count:0})]);setTasks((t||[]) as Task[]);setProjectCount(p||0);setCorrection(c||0);setReceivable((r||[]).reduce((a:any,x:any)=>a+Number(x.receivable||0),0));setQuoteAmount((q||[]).reduce((a:any,x:any)=>a+Number(x.total_amount||0),0));setAccepted((q||[]).filter((x:any)=>x.status==='수주').length);setPendingApproval(a||0);setTaxMissing(tx||0)})()},[staff?.id,staff?.role,staff?.permissions])
 const today=new Date().toISOString().slice(0,10);const dueToday=tasks.filter(x=>x.due_date===today).length;const overdue=tasks.filter(x=>x.due_date&&x.due_date<today).length
 return <><div className="pageHead"><div><h1>오늘 업무</h1><p>{staff?.name}님, 견적·프로젝트·수금 현황을 한눈에 확인하세요.</p></div></div><div className="grid4"><div className="card metric"><span>오늘 마감</span><strong>{dueToday}건</strong></div><div className="card metric"><span>진행 프로젝트</span><strong>{projectCount}건</strong></div><div className="card metric"><span>보완 프로젝트</span><strong>{correction}건</strong></div><div className="card metric"><span>총 미수금</span><strong>{receivable.toLocaleString()}원</strong></div></div><div className="grid4 dashboardSecond"><div className="card metric"><span>이번 달 견적액</span><strong>{quoteAmount.toLocaleString()}원</strong></div><div className="card metric"><span>이번 달 수주</span><strong>{accepted}건</strong></div></div><div className="card briefingCard section"><h2>오늘의 업무 브리핑</h2><div className="briefingGrid"><div><span>오늘 마감</span><b>{dueToday}건</b></div><div><span>지연 업무</span><b>{overdue}건</b></div><div><span>보완</span><b>{correction}건</b></div><div><span>미수금</span><b>{receivable.toLocaleString()}원</b></div><div><span>승인대기</span><b>{pendingApproval}건</b></div><div><span>세금계산서 미발행</span><b>{taxMissing}건</b></div></div></div><div className="section"><h2>우선 처리 업무</h2><div className="tableWrap"><table><thead><tr><th>업무</th><th>프로젝트</th><th>담당</th><th>마감</th><th>상태</th></tr></thead><tbody>{tasks.map(x=><tr key={x.id}><td><b>{x.title}</b></td><td>{x.project?.project_name||'-'}</td><td>{x.assignee?.name||'-'}</td><td>{x.due_date||'-'}</td><td><span className={'badge '+(x.status==='보완'?'danger':'')}>{x.status}</span></td></tr>)}{!tasks.length&&<tr><td colSpan={5} className="empty">진행 중인 업무가 없습니다.</td></tr>}</tbody></table></div></div></>
}
